config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tasks#index"
  resources :tasks
  resources :contents
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  

  validates :message, presence: true, length: {maximum: 40 }
  validates :image, presence: true

end

app/models/priority.rb
class Priority < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '絶対やる！！' },
    { id: 3, name: 'やる！！' },
    { id: 4, name: 'やれたら、やる！' }
  ]
end

app/models/task.rb
class Task < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :priority
  belongs_to :user
  

  validates :text, presence: true, length: {maximum: 40 }
  validates :priority, presence: true
  validates :priority_id, numericality: { other_than: 1 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks
  has_many :contents

  validates :name, presence: true, length: { maximum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: :index

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end


  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end


end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

  before_action :confirm_content, only: [:show, :edit, :update, :destroy]

  def index
    @contents = Content.includes(:user)
  end

  def new
    @content = Content.new
  end

  def create
    @content = Content.create(content_params)
    if @content.save
      redirect_to user_path(current_user.id)
    else
      render :new
    end
  end
 
  def show
  end

  def edit
  end

  def update
    if @content.update(content_params)
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  def destroy
    if @content.destroy
      redirect_to user_path(current_user.id)
    else
      render :show
    end
  end

  private
  def content_params
    params.require(:content).permit(:image, :message).merge(user_id: current_user.id)
  end

  def confirm_content
    @content = Content.find(params[:id])
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :confirm_task, only: [:show, :edit, :update, :destroy]


  def index
    @tasks = Task.includes(:user)
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    if @task.save
      redirect_to user_path(current_user.id)
    else
      render :new
    end
  end

  def show
    @contents = Content.where(user_id: current_user.id).sample(1)
    
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  def destroy
    if @task.destroy
      redirect_to user_path(current_user.id)
    else
      render :show
    end
  end



  private
  def task_params
    params.require(:task).permit(:text, :priority_id).merge(user_id: current_user.id)
  end

  def confirm_task
    @task = Task.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @tasks = user.tasks
    @contents = user.contents
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contents/edit.html.erb
<div>
  <div class = "container" >
    <%= form_with(model: @content, local: true) do |f| %>
      <h3>達成時に表示したい画像を選びましょう！！</h3>
      <p class = "nav-text">表示したい画像を選んでください</p>
      <%= f.file_field :image %>
      <p class = "nav-text">表示した画像に合ったメッセージを入れてみましょう</p>
      <%= f.text_field :message, placeholder: "メッセージを40文字以内で入力してください",class:"message-form-area" %><br>
      <%= f.submit "決定",class: "post-btn" %>
    <% end %>
  </div>
</div>

app/views/contents/index.html.erb
<h3>コンテンツ一覧</h3>
<div class = "foo1" >
 <% @contents.each do |content| %> 
    <%= image_tag content.image.variant(resize:'500x500') %>
    <p><%= content.message %></p>
    <span><%= link_to '詳細', content_path(content.id) %></span>
  <% end %>
</div>

app/views/contents/new.html.erb
<div>
  <div class = "container" >
    <%= form_with(model: @content, local: true) do |f| %>
      <h3>達成時に表示したい画像を選びましょう！！</h3>
      <p class = "nav-text">表示したい画像を選んでください</p>
      <%= f.file_field :image %>
      <p class = "nav-text">表示した画像に合ったメッセージを入れてみましょう</p>
      <%= f.text_field :message, placeholder: "メッセージを40文字以内で入力してください",class:"message-form-area" %><br>
      <%= f.submit "決定",class: "post-btn" %>
    <% end %>
  </div>
</div>

app/views/contents/show.html.erb
<h1>各コンテンツの詳細画面です。</h1>
<%= image_tag @content.image, class:'message-image' %>
<p class = "message-view"><%= @content.message %></p>
<p><%= link_to '編集する', edit_content_path(@content.id),class:"edit-action" %></p>
<p><%= link_to '削除する', content_path(@content.id), method: :delete,class:"delete-action" %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task28412</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class = "side-bar">
      <ul class = "nav-list">
        <% if user_signed_in? %>
          <li class = "menu"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "logout",class: "nav" %></li>
        <% else %>
          <li class = "menu"><%= link_to '新規登録', new_user_registration_path, class: "sign-up",class: "nav" %></li>
        <% end %>
        <% if user_signed_in? %>
          <li class = "menu"><%= link_to current_user.name, user_path(current_user.id), class: "user-name",class: "nav" %></li>
        <% else %>
          <li class = "menu"><%= link_to 'ログイン', new_user_session_path, class: "login",class: "nav" %></li>
        <% end %>

        <% if user_signed_in? %>
          <li class = "menu"><%= link_to 'あなたのタスク', user_path(current_user.id), class: "nav" %></li>
        <% else %>
          <li class = "menu"><%= link_to 'みんなのタスク', "/", class: "nav" %></li>
        <% end %>
        <li class = "menu"><%= link_to 'タスク入力', new_task_path, class: "nav" %></li>
        <li class = "menu"><%= link_to 'コンテンツ入力', new_content_path, class: "nav" %></li>
      </ul>
    </div>
    <main>
    <%= yield %>
    </main>
  </body>
</html>

app/views/tasks/edit.html.erb
<div>
  <div class = "container" >
    <%= form_with(model: @task, local: true) do |f| %>
      <h3>達成したいタスクを入力しましょう！</h3>
      <p class = "nav-text">優先順位</p>
      <%= f.collection_select(:priority_id, Priority.all, :id, :name, {}, {class:"priority-select"}) %>
      <p class = "nav-text">タスク</p>
      <%= f.text_field :text, placeholder: "タスクを40文字以内で入力してください" ,class: "task-form-area"%><br>
      <%= f.submit "決定",class: "post-btn" %>
    <% end %>
  </div>
</div>

app/views/tasks/index.html.erb
<h1>投稿されているタスク一覧</h1>
<h3>みんなに負けないように頑張りましょう！！</h3>
<hr>
<div class = "contents-row">
  <% @tasks.each do |task| %>
    <p>ユーザー名：<%= task.user.name%></p>
    <p>投稿日時　：<%= task.created_at %></p>
    <p>優先順位　：<%= task.priority.name %></p>
    <p>タスク　　：<%= task.text %></p>
    <hr>
  <% end %>
</div>

app/views/tasks/new.html.erb
<div>
  <div class = "container" >
    <%= form_with(model: @task, local: true) do |f| %>
      <h3>達成したいタスクを入力しましょう！</h3>
      <p class = "nav-text">優先順位</p>
      <%= f.collection_select(:priority_id, Priority.all, :id, :name, {}, {class:"priority-select"}) %>
      <p class = "nav-text">タスク</p>
      <%= f.text_field :text, placeholder: "タスクを40文字以内で入力してください",class: "task-form-area" %><br>
      <%= f.submit "決定",class: "post-btn"%>
    <% end %>
  </div>
</div>

app/views/tasks/show.html.erb
<h1>タスクの詳細画面です。</h1>
<h1><%= @task.text %></h1>
<div id = "action">
<p><%= link_to '編集する', edit_task_path(@task.id),class:"edit-action" %></p>
<p><%= link_to '削除する', task_path(@task.id), method: :delete,class:"delete-action" %></p>
<p id = "value" >評価する</p>
</div>

<div id = "value-response">
<p>このタスクを完了できましたか？</p>
<p id = "yes">YES</p>
<p id = "no" >NO</p>
</div>

<%# YES回答時の表示（80％）・再確認のYES回答時の表示（95%） %>
<div id = "response-image">
<% @contents.each do |content| %>
  <%= image_tag content.image, class:'message-image' %>
  <p class = "message-view"><%= content.message %></p> 
<% end %>
<P><%= link_to '＜＜トップに戻る＞＞',user_path(current_user.id)%></p>
</div>

<%# NO回答時の表示 %>
<div id = "cheering">
<%= image_tag "Notest1.jpeg",class:'message-image'%>
<p class = "message-view">次回は達成できるように頑張りましょう。</p>
<P><%= link_to '＜＜トップに戻る＞＞',user_path(current_user.id)%></p>
</div>

<%# YES回答時の表示（20%） %>
<div id = "answer-confirm">
<p>嘘を付いていますね？本当に達成できましたか？</p>
<p id = "yes-confirm">YES</p>
<p id = "no-confirm" >NO</p>
</div>

<%# 確認時にNOを選択した場合の表示(3パターン) %>
<div id = "scold-image1">
<%= image_tag "feartest1.jpeg",class:'message-image'%>
<p class = "message-view">あなたは見透かされている・・・</p>
<P><%= link_to '＜＜トップに戻る＞＞',user_path(current_user.id)%></p>
</div>

<div id = "scold-image2">
<%= image_tag "feartest2.jpeg",class:'message-image'%>
<p class = "message-view">気が緩んでいるぞ！！！</p>
<P><%= link_to '＜＜トップに戻る＞＞',user_path(current_user.id)%></p>
</div>

<div id = "scold-image3">
<%= image_tag "feartest3.jpeg",class:'message-image'%>
<p class = "message-view">後悔することになるぞ・・・</p>
<P><%= link_to '＜＜トップに戻る＞＞',user_path(current_user.id)%></p>
</div>

<%# 確認時にYESを選択した場合の表示（5%） %>
<div id = "special-scold-image">
<%= image_tag "specialfeartest1.jpg",class:'message-image'%>
<p class = "message-view">そろそろでしょ？再確認でも嘘をつくのは？</p>
<P><%= link_to '＜＜トップに戻る＞＞',user_path(current_user.id)%></p>
</div>

app/views/users/show.html.erb
<span class = "change-btn" id = "change-btn">表示切替</span>

<div class = "index">
  <div id = "task-index">
    <h1>あなたのタスク</h1>
    <h3>緊張感を持って取り組みましょう！</h3>
    <h3>タスクの評価を行う場合は、＜＜詳細＞＞をクリックしてください。</h3>
    <hr>
    <div class = "contents-row" >
    <% @tasks.each do |task| %>
      <p>投稿日時：<%= task.created_at %></p>
      <p>優先順位：<%= task.priority.name %></p>
      <p>タスク　：<%= task.text %></p>
      <p><%= link_to '＜＜詳細＞＞', task_path(task.id) %></p>
      <hr>
    <% end %>
    </div>
  </div>

  <div id = "content-index">
    <h1>コンテンツ一覧</h1>
    <h3>好きな画像とメッセージを予め投稿しておきましょう！！</h3>
    <h3>コンテンツの削除や編集を行う場合は、＜＜詳細＞＞をクリックしてください。</h3>
    <hr>

    <div class = "contents-row" >
    <% @contents.each do |content| %> 
      <%= image_tag content.image,class:'message-image' %>
      <p class = "message-view"><%= content.message %></p>
      <p><%= link_to '＜＜詳細＞＞', content_path(content.id) %></p>
      <hr>
    <% end %>
    </div>
  </div>
</div>